PEP8 Standards Fixes
dropbox/dropbox-sdk-python pull request #97
Opened 2017-03-15 19:46 UTC by Dmchale92

--------- BEGIN META VARIABLES --------
Project : dropbox-sdk-python
Task : PEP8 Standards Fixes
Done : 3-16-17
--------- END META VARIABLES --------

2017-03-15 22:14 UTC, posita requested changes
Thanks for the contribution!

Please consider updating the [`flake8` section of `tox.ini`](https://github.com/dropbox/dropbox-sdk-python/blob/master/tox.ini#L17-L20) and the [`MESSAGES CONTROL` section of `.pylintrc`](https://github.com/dropbox/dropbox-sdk-python/blob/master/.pylintrc#L1-L3) to reflect the changes. This will likely mean turning back on certain linter options, but some experimentation may be necessary.

2017-03-15 22:14 UTC, posita commented on example/back-up-and-restore/backup-and-restore-example.py
> +        BACKUPPATH, limit=30).entries  # pylint: disable=no-member
Breaking up this line confuses the linter. Consider instead:

```py
revisions = dbx.files_list_revisions(BACKUPPATH, limit=30)
entries = revisions.entries  # pylint: disable=no-member
```

2017-03-16 16:05 UTC, Dmchale92 commented
Broke up the revision retrieval code, and fixed a subsequent E261 error. Also added E1101 to tox.ini, it looks like MESSAGES CONTROL for .pylintrc already has locally-disabled disabled.

2017-03-17 20:30 UTC, posita approved these changes

2017-03-17 20:30 UTC, posita commented
@Dmchale92, it looks good. If you can squash commits, I'll merge. Thanks!

(As an aside, [`ez_setup.py`](https://bootstrap.pypa.io/ez_setup.py) comes from elsewhere (formerly from [PEAK](http://peak.telecommunity.com/), now from [PyPA](https://www.pypa.io/en/latest/). We might consider removing it altogether in the future and leave bootstrapping `setuptools` up to the installer. I think most modern versions of Python already include it anyway.)

2017-03-22 19:56 UTC, posita requested changes
@Dmchale92, it looks good. If you can squash commits, I'll merge. Thanks!

2017-03-22 19:56 UTC, posita commented
As an aside, [`ez_setup.py`](https://bootstrap.pypa.io/ez_setup.py) comes from elsewhere (formerly from [PEAK](http://peak.telecommunity.com/), now from [PyPA](https://www.pypa.io/en/latest/)). We might consider removing it altogether in the future and leave bootstrapping `setuptools` up to the installer. I think most modern versions of Python already include it anyway.

2020-03-30 17:26 UTC, rogebrd commented
Hello, If you are still interested in updating this piece of code, please acknowledge this message and make the necessary updates.

2022-04-16 21:49 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/dropbox/dropbox-sdk-python?pullRequest=97) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/dropbox/dropbox-sdk-python?pullRequest=97) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/dropbox/dropbox-sdk-python?pullRequest=97) it.</sub>

2026-07-13 20:49 UTC, AndreyVMarkelov commented
Thanks for the contribution. This patch predates the current generated SDK, supported Python versions, and repository tooling, and includes changes to files that no longer exist. It is no longer applicable to the current codebase, so closing as obsolete.

2026-07-13 20:49 UTC, closed without merging

2026-07-13 20:54 UTC, dmchaledev commented
I was just wondering whatever happened to this one. Glad it's resolved!